version: '2.4'
services:
  # Tensorflow serving
  serving:
    image: "ghcr.io/ufal/lindat-translation:hackathon"
    environment:
      - MODEL_NAME=uk-cs
    tty: true
    stdin_open: true
    platform: linux
  # frontend
  frontend:
    build: .
    ports:
      - 5000:5000
    environment:
      - LOCAL_SETTINGS=../.docker_config.py
    depends_on:
      - serving
    tty: true
    stdin_open: true
    platform: linux
